equinix_client_id     = "your equinix_client_id"
equinix_client_secret = "your equinix_client_secret"
project_id            = "your Equinix project ID in equinix fabric or network edge portal"
acl_template_id       = "your pre-defined Equinx ACL Template ID in equinix fabric or network edge portal"
metro_code_1          = "DA" 
metro_code_2          = "DC"
ssh_key_name          = "your predefined ssh key name in Equinix fabric or network edge portal"
login_name            = "login name (user name) for your network edge devices"
